#Pega a biblioteca dart
FROM dart

#Joga dentro do container que o main será app
COPY late.dart app.dart 

#Aqui é o comando que será rodado
ENTRYPOINT [ "dart" , "app.dart"]

#docker build -t app-dart
